# IS 470 Assignment 2: Voting Behavior

This assignment will help you understand how machine learning (ML) models such as Decision Tree (DT), Naïve Bayes (NB), and K-Nearest Neighbor (KNN), are used to solve real-world business problems such as predicting voting behavior. You’ll explore a dataset, build classification models, and evaluate their performance. This foundational project builds your skills for future assignments and gives you hands-on experience relevant to careers in data science, analytics, and business intelligence.

In [1]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Import libraries
import pandas as pd               # used for data analysis and manipulation

# import numpy as np              # pandas depends on numpy but we are not using numpy directly so I am commenting this out for clarity

import seaborn as sns             # used for data visualization (used for lots of charts, box plot, scatter plot etc...)
import matplotlib.pyplot as plt   # used for data visualization (specifically for plotting the decision tree classifier)

# note, previously we were importing specific module functions from sklearn.  This is not necessary since internally they do not have any naming conflicts
import sklearn as sk              # used for a bunch of things, DecisionTreeClassifier and more.

In [3]:
voting_behavior = pd.read_excel('/content/drive/MyDrive/IS470_data/Gaming Ballot Dataset.xls')
# Note, showing first 16 columns so that i can actually read it on my screen
voting_behavior.iloc[:, :16].head()

,State No,County No,FOR,AGAINST,TOTAL CASTE,DEPENDENT VARIABLE,BALLOT TYPE,POPULATION,PCI,MEDIUM FAMILY INCOME,SIZE OF COUNTY,POPULATION DENSITY,PERCENT WHITE,PERCENT BLACK,PERCENT OTHER,PERCENT MALE
0,1,1,42385,22992,65377,1,1,265038,15607,34618,1192.0,223.29,0.75,0.03,0.22,0.496
1,1,2,2015,1852,3867,1,1,13617,13740,23114,722.8,18.81,0.59,0.00,0.40,0.491
2,1,3,51959,48406,100365,1,1,391511,24187,44874,803.2,490.34,0.85,0.06,0.09,0.488
3,1,4,957,856,1813,1,1,5345,12816,27359,1349.4,3.99,0.74,0.00,0.26,0.510
4,1,5,942,1129,2071,0,1,4556,19017,23054,2555.9,1.77,0.93,0.00,0.07,0.495

In [4]:
# and here are the remaining columns
voting_behavior.iloc[:, 16:].head()

,PERCENT FEMALE,NO OF CHURCHES,NO OF CHURCH MEMBERS,PERCENT CHURCH MEMBERS OF POPULATION,POVERTY LEVEL,UNEMPLOYMENT RATE,AGE LESS THAN 18,AGE24,AGE44,AGE64,AGE OLDER THAN 65,MSA,PERCENT MINORITY,NO OF OLDER,NO OF YOUNGER
0,0.504,128,25110.0,0.094340,10.4,5.0,80600,22627,94724,46933,20154,1,0.25,67087,189448
1,0.509,22,2427.0,0.178522,24.8,7.0,4285,1861,4092,2114,1265,2,0.40,3379,8184
2,0.512,180,58252.0,0.147909,5.9,3.0,111243,29574,150740,70783,29171,1,0.15,99954,301480
3,0.490,14,1151.0,0.213821,16.9,5.0,1647,229,1670,1178,621,2,0.26,1799,3340
4,0.505,23,982.0,0.217305,19.0,1.0,1192,220,1231,973,940,2,0.07,1913,2462

## Business Understanding

Basic principles of voting behavior

Sociological Factors:

  * Social class: working class may lean left, wealthy tend to lean right
  * Religion: Religious affiliation correlates with political preference
  * Ethnicity: Minority groups tend to vote for certain parties
  * Region: Certain areas may have distinct political cultures and patterns
  * Education: Higher education levels influence ideology

Psychological Factors:

  * Party identification: A long-term pyschological attachment is a strong predictor
  * Candidate Image: personal traits of candidates affect voters
  * Issue Voting: people tend to vote for candidates that support certain issues
  * Perceived performance: Rewards or punishments for incumbents

Other Factors:
  * Turnout: is a major factor tending to go one way or another as voting increases
  * Media influence: is also very important
  * Retrospective vs Prospective: Votes based on past performance or future promises.

## Data Understanding
**State and County No:**  These numbers represent states or counties (important, they are categorical not numeric)</br>
**For and Against:**  The count of voters for or against<br/>
**Total Caste:**  Sum of the previous two numbers, (highly correlated)<br/>
**Dependent Variable:**  This is the target variable<br/>
**Ballot Type:**  Could be voting method, or election type, not clear<br/>
**Population:**  (assuming of the county)<br/>
**PCI:**  Per-Capita Income?<br/>
**Medium Family Income:**  Seems pretty obvious<br/>
**Size of County:**  In what? Square miles?<br/>
**Population Density:**  Seems like this is related to Size and Population<br/>
**Percent White:** White <br/>
**Percent Black:** Black <br/>
**Percent Other:** Other <br/>
**Percent Male:** Male <br/>
**Percent Female:** Female <br/>
**No Of Churches:** # of Churches <br/>
**No Of Church Members:** # of Church Members <br/>
**Percent Church Members of Population:** Highly correlated to other data <br/>
**Poverty Level:** percentage of population? <br/>
**Unemployment Rate:** percentage of people in the labor force looking for work<br/>
**Age Less Than 18:** Children <br/>
**Age24:** I'm guessing between 18 and 24<br/>
**Age44:** I'm guessing between 24 and 44<br/>
**Age64:** I'm guessing between 44 and 64<br/>
**Age Older than 65:** Senior Citizens<br/>
**MSA:** Metropolitan Statistical Area (urban vs rural)<br/>
**Percent Minority:** How is this defined exactly?<br/>
**No of Older:** Number of older people (where is the cutoff?)<br/>
**No of Younger:** Again, what is the cutoff?<br/>

Note: A lot of these variables are directly correlated with one another so before we go figuring out any decision tree analysis or anything else, we might want to get rid of the useless/extra values.